spring:
  application:
    name: notification-service
  data:
    mongodb:
      username: mk
      password: mk
      host: localhost
      port: 27017
      authentication-database: admin
      database: notificationdb
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.mkappworks.orderservice', 'com.mkappworks.paymentservice'
        spring.json.type.mapping: orderConfirmation:com.mkappworks.notificationservice.kafka.order.OrderConfirmation, paymentConfirmation:com.mkappworks.notificationservice.kafka.payment.PaymentConfirmation
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: mk
    password: mk
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040